{
    'name': 'Vehicle Dealership Management',
    'version': '17.0.1.0.0',
    'category': 'Sales/Sales',
    'summary': 'Manage vehicles, customers, sales, and reservations',
    'description': 'Vehicle Dealership Management System',
    'author': 'Kav',
    'depends': ['base', 'sale_management', 'mail', 'contacts'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/data.xml',
        'data/cron.xml',
        'views/vehicle_views.xml',
        'views/customer_views.xml',
        'views/sale_order_views.xml',
        'wizard/reservation_report_wizard_views.xml',
        'views/reservation_views.xml',
        'views/menu.xml',
        'reports/vehicle_reports.xml',
        'data/demo_data.xml',
    ],
    'application': True,
    'license': 'LGPL-3',
}
